name: CD flow

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_ID: GITHUB_USERNAME/REPO_NAME
  IMAGE: todo

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to ghcr
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR 
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.PROJECT_ID}}/${{ env.IMAGE }}:${{ steps.vars.outputs.sha_short }}

  deploy:
    name: Deploy todo api
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install kubectl
        uses: azure/setup-kubectl@v1
        id: kubectl

      - name: install bake
        uses: azure/k8s-bake@v2
        with:
          renderEngine: 'kustomize'
          kubectl-version: 'latest'
          kustomizationPath: './k8s/'
        id: bake

      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: kubernetes-admin@kubernetes

      - name: deploy todos api
        run: |
          (cd k8s; kustomize edit set image ghcr.io/PROJECT_ID/IMAGE=ghcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ needs.build-and-push-docker-image.outputs.sha_short }})
          kubectl apply -k k8s/
